### ISSUE TITLE
My updated code

### ISSUE THREAD

**Issue by astralprogram12** [wildangunawan/Dataset-Saham-IDX#4]
Hallo, 

Terimakasih atas inspirasinya, ini hasil edit kode saya yang masih dijalankan. semoga bisa menjadi inspirasi untuk projek lainya!

best regards
hanif

https://drive.google.com/drive/folders/1Nqxxxuik-Iu-mx-JVSyo-4nILPnLwHg2?usp=sharing

**Comment by wildangunawan** [comment]
Hi mas Hanif,

Terima kasih kontribusinya. Saya coba cek namun masih error karena butuh akses ke folder Google Drivenya. Mungkin bisa dibuka aksesnya ke publik mas?

![image](https://user-images.githubusercontent.com/35158077/149882444-f305ff1c-d2ae-43d2-bd29-f54d20b47fae.png)

Trims
