### ISSUE TITLE
Apakah ini menggunakan solusi yg saya buat?

### ISSUE THREAD

**Issue by aryakdaniswara** [wildangunawan/Dataset-Saham-IDX#5]
Melihat tanggal commit dari update yang ada, saya penasaran apakah ini menggunakan scrapper yang ada di project saya? https://github.com/aryakdaniswara/IDX-Data

Repo ini sebelumnya berisi scrapper yang terhalang captcha dan tidak bisa berlanjut (pada tahun 2021). Saya membuat scrapper dengan informasi website IDX yang bisa diakses manual (yang sebelumnya ada di repo ini), kemudian di tanggal yang sama setelah saya menghasilkan data csv mentah repo proyek saya (https://github.com/aryakdaniswara/IDX-Data), repo ini berubah menjadi dataset IDX (cek update)

Saya sudah menghubungi Mas Wildan lewat Instagram (kontak yang ditemukan). Jika memang menggunakan solusi saya, akan sangat dihargai jika memberikan kredit, saya akan lengkapi di bagian repo proyek ini juga untuk scrapper agar bisa diakses orang lain jika ingin mendapat data yang lebih komprehensif. Mungkin Mas Wildan juga bisa sharing proses untuk membersihkan datanya agar bisa lebih mudah dibaca dan diakses

Terima kasih, Mas Wildan

**Comment by aryakdaniswara** [comment]
A misunderstanding! Ternyata kebetulan Mas Wildan update data di hari yg sama aku selesai update projek, Maaf banget Mas Wildan atas kesalahpahamannya, Terima kasih banyak udah meluangkan waktu buat ngobrol dan berbagi. Wish you well Mas!

**Comment by wildangunawan** [comment]
Halo Arii, yess misunderstanding aja karena kebetulan banget waktu kamu upload dan waktu aku ngerjainnya persis barengan. Scrapermu, kalo udah lebih rapian seperti yang kamu bilang, nanti aku tambahin di README.md repository ini sebagai referensi salah satu cara ambil data IDX ini, barangkali ada orang-orang yang mau lihat yaa.
