### ISSUE TITLE
Minta tolong untuk update Dataset Saham IDX

### ISSUE THREAD

**Issue by alhfzhz** [wildangunawan/Dataset-Saham-IDX#7]
Assalamualaikum, Selamat malam pak wildan, saya hafizh, saya seorang mahasiswa semester 7 dengan konsentrasi Database, kebetulan saya menggunakan dataset Pak Wildan untuk TA saya, nah dari dosen nya itu dia pengen Data terbaru kalo mengambil dataset ini, jadi saya mohon minta tolong Pak Wildan untuk Update Dataset Stock Market IDX ini, 
Terima kasih Pak Wildan

**Comment by wildangunawan** [comment]
Selamat pagi mas,

Datanya sudah saya update sampai dengan kemarin (15 November 2023) ya mas. Terima kasih juga sudah kasih saya jajan wkwkwk

**Comment by alhfzhz** [comment]
hehehehe hatur nuhun mas wkwkwk
maaf gk seberapa mas hihi
sepertinya mas nya ini expert di bidang data ya? terutama di stock market

**Comment by wildangunawan** [comment]
Wkwkwk, enggak, enthusiast aja apalagi juga invest di stock. Jadi pengen aja punya dataset ini karena sebelumnya ngga ada.

Kalau sudah aman semua, aku close ya issuenya. Makasi banyak sekali lagi mas Hafizh :)
